### Simulation of a quantum computer


In [36]:
#Alpha beta Convention taken from Michael Nielsen's Youtube series 'Quantum Computing for the Determined'

from random import random, randint

In [37]:
class qubit(object) :
    def __init__(self) :
        self.alpha = random()
        self.beta = (1 - self.alpha**2)**0.5
        self.measured = False
    
    def isValid(self, a, b) :
        if ((a**2 + b**2) > 1) or (a < 0) or (b < 0) or (a > 1) or (b > 1) or self.measured:
            return False
        else :
            return True
    def setStates(self, a, b) :
        if self.isValid(a, b) and not self.measured:
            self.alpha = a
            self.beta = b
            return True
        else :
            return False
    def getStates(self) :
        #only for verification, remove in end
        if not self.measured :
            return self.alpha, self.beta
        else :
            return False
    def negate(self):
        if not self.measured :
            self.alpha, self.beta = self.beta, self.alpha

    def hadamard(self) :
        if self.measured :
            return
        root2 = 2**0.5
        a = self.alpha + self.beta
        b = self.alpha - self.beta
        self.alpha = a/root2
        self.beta = b/root2
    
    def measure(self) :
        #not accurate probabilites
        if not self.measured :
            lim = 5 #10^lim will be the size of list
            proba = int(str(self.alpha**2)[2:lim+2])
            probb = 10**lim - proba
            L = [0 for x in range(proba)]
            for i in range(probb) : L.insert(randint(0, 10**lim-1), 1)
            result = L[randint(0, 10**lim-1)]
            self.measured = True #You lose the values of alpha and beta now
            del self.alpha
            del self.beta
            return result




In [6]:
a = qubit()
print(a.getStates())
print(a.measure())


(0.6820147925295239, 0.7313383777506213)
1


In [ ]:

'''
Float precision is only upto 16 decimal places which is going to be a drawback later
So I plan on making the '0.' irrelevant and make use of the infinite (i think) integer precision
that python offers. First priority is to get the fundamentals are right
'''

----------------------------------------------------------------------------END-----------------------------------------------------------------------------------------------------------------------------

In [7]:
import cmath
import math
import numpy as np
import scipy as sp

In [ ]:
posi = complex(0, 1)
negi = complex(0, -1)

#Zero State |0>
zero = np.matrix([[1],[0]])

#One State |1>
one = np.matrix([[0],[1]])

#Plus State |+>
plus = 1/math.sqrt(2) * np.matrix([[1],[1]])

#Minus State |->
minus = 1/math.sqrt(2) * np.matrix([[1],[-1]])

In [12]:
class gates:

    """ONE QBIT"""
    #NOT Gate
    def xgate(qinput):
        xmat = np.matrix([[0, 1],
                        [1, 0]])
        return np.dot(xmat, qinput)

    #Sqaure Root NOT Gate
    def sqrtxgate(qinput):
        sxmat = np.matrix([[posi, negi],
                        [negi, posi]])
        return np.dot(sxmat, qinput)

    #Z Gate
    def zgate(qinput):
        zmat = np.matrix([[1, 0],
                        [0, -1]])
        return np.dot(zmat, qinput)

    #Y Gate
    def ygate(qinput):
        ymat = np.matrix([[0, negi],
                        [posi, 0]])
        return np.dot(ymat, qinput)

    #Hadamard Gate
    def hadamard(qinput):
        hmat = 1/math.sqrt(2) * np.matrix([[1, 1],
                                        [1, -1]])
        return np.dot(hmat, qinput)

    """TWO QBITS"""
    #CNOT Gate
    def cnot(qbitone, qinput):
        cmat = np.matrix([[1, 0, 0, 0],
                        [0, 1, 0, 0],
                        [1, 0, 0, 1],
                        [0, 1, 1, 0]])
        retarr = np.dot(cmat, qinput)
        np.put(retarr, [0, 1], [qbitone[0], qbitone[1]])
        return retarr

    #Swap Gate
    def swap(qinput):
        smat = np.matrix([[1, 0, 0, 0],
                        [0, 0, 1, 0],
                        [0, 1, 0, 0],
                        [0, 0, 0, 1]])
        return np.dot(smat, qinput)

    #Square Root Swap
    def sqrtswap(qinput):
        ssmat = np.matrix([[1, 0, 0, 0],
                        [0 , 1/2 * posi, 1/2 * negi, 0],
                        [0, 1/2 * negi, 1/2 * posi, 0],
                        [0, 0, 0, 1]])
        return np.dot(ssmat, qinput)

    #Ising (XX) Gate
    def ising(qinput, qphi):
        imat = 1/math.sqrt(2) * np.matrix([[1, 0, 0, cmath.exp(posi*(1 - math.pi/2))],
                                        [0, 1, negi, 0],
                                        [0, negi, 1, 0],
                                        [cmath.exp(posi*(1 - math.pi/2)), 0, 0, 1]])
        return np.dot(imat, qinput)

    """THREE QBITS"""
    #Toffoli Gate
    def toffoli(qinput):
        tmat = np.matrix([[1, 0, 0, 0, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0],
                        [0, 0, 1, 0, 0, 0, 0, 0],
                        [0, 0, 0, 1, 0, 0, 0, 0],
                        [0, 0, 0, 0, 1, 0, 0, 0],
                        [0, 0, 0, 0, 0, 1, 0, 0],
                        [1, 0, 0, 0, 0, 0, 0, 1],
                        [1, 0, 0, 0, 0, 0, 1, 0]])
        return np.dot(tmat, qinput)

    #Fredkin Gate
    def fredkin(qinput):
        fmat = np.matrix([[1, 0, 0, 0, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0],
                        [0, 0, 1, 0, 0, 0, 0, 0],
                        [0, 0, 0, 1, 0, 0, 0, 0],
                        [0, 0, 0, 0, 1, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 1, 0],
                        [1, 0, 0, 0, 0, 1, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 1]])
        return np.dot(fmat, qinput)

    #Peres Gate
    def peres(qinput):
        pmat = np.matrix([[1, 0, 0, 0, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0],
                        [0, 0, 1, 0, 0, 0, 0, 0],
                        [0, 0, 0, 1, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 1, 0],
                        [0, 0, 0, 0, 0, 0, 0, 1],
                        [0, 0, 0, 0, 0, 1, 0, 0],
                        [0, 0, 0, 0, 1, 0, 0, 0]])
        return np.dot(pmat, qinput)

    """INF QBITS"""
    #CU Gate
    def cu(qinput):
        qtemp = qinput
        print(qinput[[0]])
        if qtemp[[0]] == 1:
            for i in range(len(qtemp)):
                qtemp[i + 1] = gates.xgate(qinput[i + 1])
            return qtemp



In [16]:
class assembly:

    def nkron(*args):
        result = np.array([[1]])
        for op in args:
            result = np.kron(result, op)
        return result

In [42]:
qin0 = np.matrix('1;0;0;0;0;0;0;0') #|0>
qin1 = np.matrix('0;1') #|1>
qrand = np.matrix('0.86602540378;0.5')

##### Hadamard preserves length

In [28]:
gates.hadamard(qin0)

matrix([[0.70710678],
        [0.70710678]])

In [30]:
gates.hadamard(qin1)

matrix([[ 0.70710678],
        [-0.70710678]])

In [38]:
gates.hadamard(qrand)

matrix([[0.96592583],
        [0.25881905]])

In [43]:
gates.fredkin(qin0)

matrix([[1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0]])